version: '3'

services:
    #NGNIX server
    web:
        ports:
          - 1001:80
        volumes:
          - '.:/var/www/html/docker-demo/public/'
          - './docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf'
          - './var/logs/nginx/:/var/log/nginx'

    #PHP Of course :-)
    php:
        volumes:
          - '.:/var/www/html/docker-demo'
        ports:
          - '9000:9000'

    #MySql
    mydockersql:
        environment:
            MYSQL_ROOT_PASSWORD: dockpwd
            MYSQL_USER: test
            MYSQL_DATABASE: docker_demo


    #Tools needed (composer,...)
    tools:
        volumes:
          - ./:/var/www/html/docker-demo/
        working_dir: /var/www/html/docker-demo/